// templates/nextjs-example/src/components/login-with-ii.tsx
import { Button } from "@/components/button";
import { signIn } from "@junobuild/core";

export const LoginWithII = () => {
  const signWithII = async () => {
    await signIn({
      internet_identity: {},
    });
  };

  return <Button onClick={signWithII}>Continue with Internet Identity</Button>;
};

// templates/angular-example/src/app/components/login-with-ii/login-with-ii.component.ts
import { Component } from '@angular/core';
import { signIn } from '@junobuild/core';
import { ButtonComponent } from '../button/button.component';

@Component({
  selector: 'app-login-with-ii',
  imports: [ButtonComponent],
  templateUrl: './login-with-ii.component.html',
})
export class LoginComponentWithII {
  readonly signIn = signIn;
}

<app-button (click)="signIn({ internet_identity: {} })"
  >Continue with Internet Identity</app-button
>
