// templates/nextjs-example/src/components/backdrop.tsx
interface BackdropProps {
  spinner?: boolean;
}

export const Backdrop = ({spinner = false}: BackdropProps) => (
  <div className="fixed inset-0 z-40 bg-white/30 dark:bg-lavender-blue-200/40 flex items-center justify-center backdrop-blur-xl">
    {spinner && (
      <div
        className="w-12 h-12 rounded-full animate-spin
                    border-[3px] border-solid border-lavender-blue-600 border-t-transparent"></div>
    )}
  </div>
);

// templates/angular-example/src/app/components/backdrop/backdrop.component.ts
import { Component, input, Input } from '@angular/core';

@Component({
  selector: 'app-backdrop',
  templateUrl: './backdrop.component.html',
})
export class BackdropComponent {
  spinner = input(false);
}

<div
  class="dark:bg-lavender-blue-200/40 fixed inset-0 z-40 flex items-center justify-center bg-white/30 backdrop-blur-xl"
>
  @if (spinner()) {
    <div
      class="border-lavender-blue-600 h-12 w-12 animate-spin rounded-full border-[3px] border-solid border-t-transparent"
    ></div>
  }
</div>
