// templates/react-ts-example/src/components/Login.tsx
import { signIn } from "@junobuild/core";
import { FC } from "react";
import { Button } from "./Button";

export const Login: FC = () => {
  const signWithII = async () => {
    await signIn({
      internet_identity: {},
    });
  };

  return <Button onClick={signWithII}>Continue with Internet Identity</Button>;
};

// templates/angular-example/src/app/components/login/login.component.ts
import {Component} from '@angular/core';
import {signIn} from '@junobuild/core';
import {ButtonComponent} from '../button/button.component';

@Component({
  selector: 'app-login',
  imports: [ButtonComponent],
  templateUrl: './login.component.html'
})
export class LoginComponent {
  readonly signIn = signIn;
}

<div class="gap flex flex-col">
  <app-passkey />

  <app-button (click)="signIn({ internet_identity: {} })"
    >Continue with Internet Identity</app-button
  >
</div>
