// templates/angular-example/src/app/components/passkey/use-passkey/use-passkey.component.ts
import { Component, computed, input } from '@angular/core';
import {
  signIn,
  SignProgress,
  SignProgressFn,
  WebAuthnSignInProgressStep,
} from '@junobuild/core';
import type { PasskeyProgress } from '../../../types/passkey';
import { ButtonComponent } from '../../button/button.component';
import { ProgressComponent } from '../progress/progress.component';

type ProgressSignIn = SignProgress<WebAuthnSignInProgressStep> | undefined | null;

@Component({
  selector: 'app-use-passkey',
  imports: [ButtonComponent, ProgressComponent],
  templateUrl: './use-passkey.component.html',
})
export class UsePasskeyComponent {
  readonly WebAuthnSignInProgressStep = WebAuthnSignInProgressStep;

  readonly wizardProgress = input.required<PasskeyProgress | undefined>();
  wizardOnProgress =
    input.required<(progress: PasskeyProgress | undefined) => void>();

  readonly #computedProgress = computed<ProgressSignIn>(() => {
    const progress = this.wizardProgress();

    return progress === undefined
      ? undefined
      : "signIn" in progress ? progress.signIn : null;
  });

  get progress(): ProgressSignIn {
    return this.#computedProgress();
  }

  async doSignIn () {
    const onProgress: SignProgressFn<WebAuthnSignInProgressStep> = (progress) =>
      this.wizardOnProgress()({ signIn: progress });

    try {
      await signIn({
        webauthn: {
          options: { onProgress },
        },
      });
    } catch (error: unknown) {
      this.wizardOnProgress()(undefined);

      // IRL the error would be gracefully displayed to the user unless
      // it is one to ignore - for example when the user cancel the flow.
      throw error;
    }
  };
}

@if (progress === undefined) {
  <p class="pt-6">Already got one set-up?</p>

  <app-button (click)="doSignIn()">Use your passkey</app-button>
} @else if (progress !== null) {
  <app-progress>
    @if (progress.step === WebAuthnSignInProgressStep.RequestingUserCredential) {
      <span>Requesting user credential...</span>
    }
    @if (progress.step === WebAuthnSignInProgressStep.FinalizingCredential) {
      <span>Finalizing credential...</span>
    }
    @if (progress.step === WebAuthnSignInProgressStep.Signing) {
      <span>Signing request...</span>
    }
    @if (progress.step === WebAuthnSignInProgressStep.FinalizingSession) {
      <span>Finalizing session...</span>
    }
    @if (progress.step === WebAuthnSignInProgressStep.RetrievingUser) {
      <span>Loading user...</span>
    }
  </app-progress>
}

// templates/react-example/src/components/passkey/UsePasskey.jsx
import { signIn, WebAuthnSignInProgressStep } from "@junobuild/core";
import { useEffect, useState } from "react";
import { Button } from "../Button.jsx";
import { Progress } from "./Progress.jsx";
import PropTypes from "prop-types";

export const UsePasskey = ({
  progress: wizardProgress,
  onProgress: wizardOnProgress,
}) => {
  const [progress, setProgress] = useState(undefined);

  const onProgress = (progress) => wizardOnProgress({ signIn: progress });

  useEffect(() => {
    if (wizardProgress === undefined) {
      setProgress(undefined);
      return;
    }

    setProgress("signIn" in wizardProgress ? wizardProgress.signIn : null);
  }, [wizardProgress]);

  const doSignIn = async () => {
    try {
      await signIn({
        webauthn: {
          options: { onProgress },
        },
      });
    } catch (error) {
      wizardOnProgress(undefined);

      // IRL the error would be gracefully displayed to the user unless
      // it is one to ignore - for example when the user cancel the flow.
      throw error;
    }
  };

  return (
    <>
      {progress === null ? (
        <></>
      ) : progress === undefined ? (
        <>
          <p className="pt-6">Already got one set-up?</p>

          <Button onClick={doSignIn}>Use your passkey</Button>
        </>
      ) : (
        <Progress>
          {progress?.step ===
            WebAuthnSignInProgressStep.RequestingUserCredential && (
            <span>Requesting user credential...</span>
          )}
          {progress?.step ===
            WebAuthnSignInProgressStep.FinalizingCredential && (
            <span>Finalizing credential...</span>
          )}
          {progress?.step === WebAuthnSignInProgressStep.Signing && (
            <span>Signing request...</span>
          )}
          {progress?.step === WebAuthnSignInProgressStep.FinalizingSession && (
            <span>Finalizing session...</span>
          )}
          {progress?.step === WebAuthnSignInProgressStep.RetrievingUser && (
            <span>Loading user...</span>
          )}
        </Progress>
      )}
    </>
  );
};

UsePasskey.propTypes = {
  progress: PropTypes.object.isRequired,
  onProgress: PropTypes.func.isRequired,
};
