// templates/vue-example/src/components/passkey/UsePasskey.vue
<script setup lang="ts">
import type { PasskeyProgress } from '@/types/passkey.ts'
import { computed } from 'vue'
import {
  signIn,
  type SignProgress,
  type SignProgressFn,
  WebAuthnSignInProgressStep,
} from '@junobuild/core'
import Button from '@/components/Button.vue'
import Progress from '@/components/passkey/Progress.vue'

const { progress: wizardProgress, onProgress: wizardOnProgress } = defineProps<{
  progress: PasskeyProgress | undefined
  onProgress: (progress: PasskeyProgress | undefined) => void
}>()

const progress = computed<SignProgress<WebAuthnSignInProgressStep> | undefined | null>(() =>
  wizardProgress === undefined
    ? undefined
    : 'signIn' in wizardProgress
      ? wizardProgress.signIn
      : null,
)

const onProgress: SignProgressFn<WebAuthnSignInProgressStep> = (p) => {
  wizardOnProgress({ signIn: p })
}

const doSignIn = async () => {
  try {
    await signIn({
      webauthn: { options: { onProgress } },
    })
  } catch (error: unknown) {
    wizardOnProgress(undefined)

    throw error
  }
}
</script>

<template>
  <template v-if="progress === undefined">
    <p class="pt-6">Already got one set-up?</p>

    <Button @click="doSignIn">Use your passkey</Button>
  </template>

  <template v-else-if="progress !== null">
    <Progress>
      <span v-if="progress.step === WebAuthnSignInProgressStep.RequestingUserCredential">
        Requesting user credential...
      </span>
      <span v-else-if="progress.step === WebAuthnSignInProgressStep.FinalizingCredential">
        Finalizing credential...
      </span>
      <span v-else-if="progress.step === WebAuthnSignInProgressStep.Signing">
        Signing request...
      </span>
      <span v-else-if="progress.step === WebAuthnSignInProgressStep.FinalizingSession">
        Finalizing session...
      </span>
      <span v-else-if="progress.step === WebAuthnSignInProgressStep.RetrievingUser">
        Loading user...
      </span>
    </Progress>
  </template>
</template>

// templates/sveltekit-example/src/lib/components/passkey/UsePasskey.svelte
<script lang="ts">
	import {
		signIn,
		type SignProgress,
		type SignProgressFn,
		WebAuthnSignInProgressStep
	} from '@junobuild/core';
	import type { PasskeyProps } from '$lib/types/passkey';
	import Button from '$lib/components/Button.svelte';
	import Progress from '$lib/components/passkey/Progress.svelte';

	let { progress: wizardProgress, onProgress: wizardOnProgress }: PasskeyProps = $props();

	const progress = $derived<SignProgress<WebAuthnSignInProgressStep> | undefined | null>(
		wizardProgress === undefined
			? undefined
			: 'signIn' in wizardProgress
				? wizardProgress.signIn
				: null
	);

	const onProgress: SignProgressFn<WebAuthnSignInProgressStep> = (p) => {
		wizardOnProgress({ signIn: p });
	};

	const doSignIn = async () => {
		try {
			await signIn({
				webauthn: { options: { onProgress } }
			});
		} catch (error: unknown) {
			wizardOnProgress(undefined);

			throw error;
		}
	};
</script>

{#if progress === undefined}
	<p class="pt-6">Already got one set-up?</p>

	<Button onclick={doSignIn}>Use your passkey</Button>
{:else if progress !== null}
	<Progress>
		{#if progress.step === WebAuthnSignInProgressStep.RequestingUserCredential}
			<span>Requesting user credential...</span>
		{:else if progress.step === WebAuthnSignInProgressStep.FinalizingCredential}
			<span>Finalizing credential...</span>
		{:else if progress.step === WebAuthnSignInProgressStep.Signing}
			<span>Signing request...</span>
		{:else if progress.step === WebAuthnSignInProgressStep.FinalizingSession}
			<span>Finalizing session...</span>
		{:else if progress.step === WebAuthnSignInProgressStep.RetrievingUser}
			<span>Loading user...</span>
		{/if}
	</Progress>
{/if}
