// templates/nextjs-example/src/components/passkey/use-passkey.tsx
import { Button } from "@/components/button";
import {
  signIn,
  WebAuthnSignInProgressStep,
  type SignProgress,
  type SignProgressFn,
} from "@junobuild/core";
import { useEffect, useState } from "react";
import { Progress } from "@/components/passkey/progress";
import { PasskeyProps } from "@/types/passkey";

export const UsePasskey = ({
  progress: wizardProgress,
  onProgress: wizardOnProgress,
}: PasskeyProps) => {
  const [progress, setProgress] = useState<
    SignProgress<WebAuthnSignInProgressStep> | undefined | null
  >(undefined);

  const onProgress: SignProgressFn<WebAuthnSignInProgressStep> = (
    progress,
  ) => wizardOnProgress({ signIn: progress });

  useEffect(() => {
    if (wizardProgress === undefined) {
      setProgress(undefined);
      return;
    }

    setProgress("signIn" in wizardProgress ? wizardProgress.signIn : null);
  }, [wizardProgress]);

  const doSignIn = async () => {
    try {
      await signIn({
        webauthn: {
          options: { onProgress },
        },
      });
    } catch (error: unknown) {
      wizardOnProgress(undefined);

      // IRL the error would be gracefully displayed to the user unless
      // it is one to ignore - for example when the user cancel the flow.
      throw error;
    }
  };

  return (
    <>
      {progress === null ? (
        <></>
      ) : progress === undefined ? (
        <>
          <p className="pt-6">Already got one set-up?</p>

          <Button onClick={doSignIn}>Use your passkey</Button>
        </>
      ) : (
        <Progress>
          {progress?.step ===
            WebAuthnSignInProgressStep.RequestingUserCredential && (
            <span>Requesting user credential...</span>
          )}
          {progress?.step ===
            WebAuthnSignInProgressStep.FinalizingCredential && (
            <span>Finalizing credential...</span>
          )}
          {progress?.step === WebAuthnSignInProgressStep.Signing && (
            <span>Signing request...</span>
          )}
          {progress?.step === WebAuthnSignInProgressStep.FinalizingSession && (
            <span>Finalizing session...</span>
          )}
          {progress?.step === WebAuthnSignInProgressStep.RetrievingUser && (
            <span>Loading user...</span>
          )}
        </Progress>
      )}
    </>
  );
};

// templates/sveltekit-example/src/lib/components/passkey/UsePasskey.svelte
<script lang="ts">
	import {
		signIn,
		type SignProgress,
		type SignProgressFn,
		WebAuthnSignInProgressStep
	} from '@junobuild/core';
	import type { PasskeyProps } from '$lib/types/passkey';
	import Button from '$lib/components/Button.svelte';
	import Progress from '$lib/components/passkey/Progress.svelte';

	let { progress: wizardProgress, onProgress: wizardOnProgress }: PasskeyProps = $props();

	const progress = $derived<SignProgress<WebAuthnSignInProgressStep> | undefined | null>(
		wizardProgress === undefined
			? undefined
			: 'signIn' in wizardProgress
				? wizardProgress.signIn
				: null
	);

	const onProgress: SignProgressFn<WebAuthnSignInProgressStep> = (p) => {
		wizardOnProgress({ signIn: p });
	};

	const doSignIn = async () => {
		try {
			await signIn({
				webauthn: { options: { onProgress } }
			});
		} catch (error: unknown) {
			wizardOnProgress(undefined);

			throw error;
		}
	};
</script>

{#if progress === undefined}
	<p class="pt-6">Already got one set-up?</p>

	<Button onclick={doSignIn}>Use your passkey</Button>
{:else if progress !== null}
	<Progress>
		{#if progress.step === WebAuthnSignInProgressStep.RequestingUserCredential}
			<span>Requesting user credential...</span>
		{:else if progress.step === WebAuthnSignInProgressStep.FinalizingCredential}
			<span>Finalizing credential...</span>
		{:else if progress.step === WebAuthnSignInProgressStep.Signing}
			<span>Signing request...</span>
		{:else if progress.step === WebAuthnSignInProgressStep.FinalizingSession}
			<span>Finalizing session...</span>
		{:else if progress.step === WebAuthnSignInProgressStep.RetrievingUser}
			<span>Loading user...</span>
		{/if}
	</Progress>
{/if}
