// templates/sveltekit-example/src/lib/components/Background.svelte
<div
	class="hidden sm:block fixed top-[400px] [@media(min-height:800px)]:top-2/4 right-0 -z-10 translate-x-2/4 lg:translate-x-1/3 -translate-y-2/4 min-h-[800px] h-[100dvh] aspect-square"
>
	<img
		src="/juno_illustration.svg"
		role="presentation"
		loading="lazy"
		alt="An astronaut floating in space around planet Juno orbited by satellites, stars in the background."
	/>
</div>

// templates/react-ts-starter/src/components/Background.tsx
import { FC } from "react";

export const Background: FC = () => {
  return (
    <div className="fixed top-[400px] right-0 -z-10 hidden aspect-square h-[100dvh] min-h-[800px] -translate-y-2/4 translate-x-2/4 sm:block lg:translate-x-1/3 [@media(min-height:800px)]:top-2/4">
      <img
        src="./juno_illustration.svg"
        role="presentation"
        loading="lazy"
        alt="An astronaut floating in space around planet Juno orbited by satellites, stars in the background."
      />
    </div>
  );
};
