// templates/vue-example/src/components/Auth.vue
<script setup lang="ts">
import { useAuthStore } from '@/stores/auth.store'
import { storeToRefs } from 'pinia'
import Login from './Login.vue'
import Passkey from './passkey/Passkey.vue'
import Logout from './Logout.vue'

const store = useAuthStore()
const { user } = storeToRefs(store)
</script>

<template>
  <template v-if="user !== undefined && user !== null">
    <div>
      <slot />

      <Logout />
    </div>
  </template>

  <template v-else>
    <div class="gap flex flex-col">
      <Passkey />

      <Login />
    </div>
  </template>
</template>

// templates/react-ts-example/src/components/Auth.tsx
import { onAuthStateChange, User } from "@junobuild/core";
import {
  createContext,
  FC,
  PropsWithChildren,
  useEffect,
  useState,
} from "react";
import { Login } from "./Login";
import { Logout } from "./Logout";
import { Passkey } from "./passkey/Passkey.tsx";

export const AuthContext = createContext<{ user: User | null }>({ user: null });

export const Auth: FC<PropsWithChildren> = (props) => {
  const { children } = props;
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    const sub = onAuthStateChange((user) => setUser(user));

    return () => sub();
  }, []);

  return (
    <AuthContext.Provider value={{ user }}>
      {user !== null ? (
        <div>
          {children}

          <Logout />
        </div>
      ) : (
        <div className="gap flex flex-col">
          <Passkey />
          <Login />
        </div>
      )}
    </AuthContext.Provider>
  );
};
