// templates/sveltekit-example/src/lib/components/Backdrop.svelte
<script lang="ts">
	interface Props {
		spinner?: boolean;
	}

	let { spinner = false }: Props = $props();
</script>

<div
	class:backdrop-blur-sm={spinner}
	class:backdrop-blur-xl={!spinner}
	class="fixed inset-0 z-40 bg-white/30 flex items-center justify-center"
>
	{#if spinner}
		<div
			class="w-12 h-12 rounded-full animate-spin border-[3px] border-solid border-lavender-blue-600 border-t-transparent"
		></div>
	{/if}
</div>

// templates/react-ts-example/src/components/Backdrop.tsx
import { FC } from 'react'

interface BackdropProps {
  spinner?: boolean
}

export const Backdrop: FC<BackdropProps> = (props) => {
  const { spinner = false } = props

  return (
    <div
      className={`fixed inset-0 z-40 ${spinner ? 'backdrop-blur-sm' : 'backdrop-blur-xl'} bg-white/30 flex items-center justify-center`}>
      {spinner && (
        <div
          className="w-12 h-12 rounded-full animate-spin
          border-[3px] border-solid border-lavender-blue-600 border-t-transparent"></div>
      )}
    </div>
  )
}
