// templates/react-ts-starter/src/components/Article.tsx
import { FC, PropsWithChildren } from "react";

interface ArticleProps extends PropsWithChildren {
  href: string;
  ariaLabel: string;
  title: string;
}

export const Article: FC<ArticleProps> = (props) => {
  const { href, ariaLabel, children, title } = props;
  return (
    <a
      href={href}
      rel="noreferrer noopener"
      target="_blank"
      aria-label={ariaLabel}
      className="group dark:border-lavender-blue-500 hover:bg-lavender-blue-200 active:bg-lavender-blue-400 flex flex-col rounded-sm border-[3px] border-black bg-white px-4 py-3 shadow-[8px_8px_0px_rgba(0,0,0,1)] transition-all active:translate-x-[8px] active:translate-y-[8px] active:shadow-none dark:bg-black dark:text-white dark:shadow-[8px_8px_0px_#7888FF] dark:hover:border-white dark:hover:bg-black dark:hover:shadow-[8px_8px_0px_#fff] dark:active:bg-black"
    >
      <h4 className="dark:text-lavender-blue-500 mb-1 font-extrabold break-words sm:text-lg dark:group-hover:text-white">
        {title}
      </h4>

      <p className="mb-2">{children}</p>
    </a>
  );
};

// templates/sveltekit-starter/src/lib/components/Article.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		href: string;
		ariaLabel: string;
		title: string;
		children: Snippet;
	}

	let { href, ariaLabel, title, children }: Props = $props();
</script>

<a
	{href}
	rel="noreferrer noopener"
	target="_blank"
	aria-label={ariaLabel}
	class="group flex flex-col py-3 px-4 border-black dark:border-lavender-blue-500 dark:hover:border-white border-[3px] rounded bg-white dark:bg-black dark:text-white transition-all shadow-[8px_8px_0px_rgba(0,0,0,1)] dark:shadow-[8px_8px_0px_#7888FF] dark:hover:shadow-[8px_8px_0px_#fff] hover:bg-lavender-blue-200 dark:hover:bg-black active:bg-lavender-blue-400 dark:active:bg-black active:shadow-none active:translate-x-[8px] active:translate-y-[8px]"
>
	<h4
		class="sm:text-lg break-words font-extrabold mb-1 dark:text-lavender-blue-500 group-hover:dark:text-white"
	>
		{title}
	</h4>

	<p class="mb-2">{@render children()}</p>
</a>
