// templates/vue-starter/src/components/Background.vue
<template>
  <div
    class="fixed top-[400px] right-0 -z-10 hidden aspect-square h-[100dvh] min-h-[800px] translate-x-2/4 -translate-y-2/4 sm:block lg:translate-x-1/3 [@media(min-height:800px)]:top-2/4"
  >
    <img
      src="/juno_illustration.svg"
      role="presentation"
      loading="lazy"
      alt="An astronaut floating in space around planet Juno orbited by satellites, stars in the background."
    />
  </div>
</template>

// templates/react-starter/src/components/Background.jsx
export const Background = () => {
  return (
    <div className="fixed top-[400px] right-0 -z-10 hidden aspect-square h-[100dvh] min-h-[800px] -translate-y-2/4 translate-x-2/4 sm:block lg:translate-x-1/3 [@media(min-height:800px)]:top-2/4">
      <img
        src="./juno_illustration.svg"
        role="presentation"
        loading="lazy"
        alt="An astronaut floating in space around planet Juno orbited by satellites, stars in the background."
      />
    </div>
  );
};
