// templates/angular-example/src/app/components/passkey/create-passkey/create-passkey.component.ts
import { Component, computed, ElementRef, input, signal, ViewChild } from '@angular/core';
import { SignProgress, SignProgressFn, signUp, WebAuthnSignUpProgressStep } from '@junobuild/core';
import { PasskeyProgress } from '../../../types/passkey';
import { ButtonComponent } from '../../button/button.component';
import { ProgressComponent } from '../progress/progress.component';

type ProgressSignUp =
  | {
  state: "init" | "setup" | "hidden";
}
  | {
  state: "progress";
  detail: SignProgress<WebAuthnSignUpProgressStep>;
};

@Component({
  selector: 'app-create-passkey',
  imports: [ButtonComponent, ProgressComponent],
  templateUrl: './create-passkey.component.html',
})
export class CreatePasskeyComponent {
  readonly WebAuthnSignUpProgressStep = WebAuthnSignUpProgressStep;

  readonly wizardProgress = input.required<PasskeyProgress | undefined>();
  wizardOnProgress = input.required<(progress: PasskeyProgress | undefined) => void>();

  @ViewChild('inputText') readonly inputText: ElementRef<HTMLInputElement> | undefined;
  passkeyDisplayName = signal<string>('');

  readonly #computedProgress = computed<ProgressSignUp>(() => {
    const progress = this.wizardProgress();

    return progress === undefined ? { state: "init" } : (
      "signUp" in progress
        ? { state: "progress", detail: progress.signUp }
        : "setup" in progress
          ? { state: "setup" }
          : { state: "hidden" }
    )
  });

  get progress(): ProgressSignUp {
    return this.#computedProgress();
  }

  goToSetup() {
    this.wizardOnProgress()({ setup: null });
  }

  async doSignUp() {
    try {
      const onProgress: SignProgressFn<WebAuthnSignUpProgressStep> = (progress) =>
        this.wizardOnProgress()({ signUp: progress });

      await signUp({
        webauthn: {
          options: {
            onProgress,
            ...(this.passkeyDisplayName() !== '' && {
              passkey: {
                user: {
                  displayName: this.passkeyDisplayName(),
                },
              },
            }),
          },
        },
      });
    } catch (error: unknown) {
      this.wizardOnProgress()(undefined);

      // IRL the error would be gracefully displayed to the user unless
      // it is one to ignore - for example when the user cancel the flow.
      throw error;
    }
  };

  onInputChange() {
    this.passkeyDisplayName.set(this.inputText?.nativeElement.value ?? "");
  }
}

@if (progress.state === 'init') {
  <p>
    First time here? Use your device (Face ID, Windows Hello, or screen lock) to get in.
  </p>

  <app-button (click)="goToSetup()">Create a new passkey</app-button>
}

@if (progress.state === 'setup') {
  <p>Want to give it a nickname so you'll spot it easily later?</p>

  <input
    class="mx-0 mt-2 mb-6 block w-full resize-none rounded-sm border-[3px] border-black bg-white px-3 py-1.5 text-base font-normal shadow-[5px_5px_0px_rgba(0,0,0,1)] focus:outline-hidden"
    placeholder="An optional nickname"
    [value]="passkeyDisplayName()"
    (input)="onInputChange()"
    #inputText
  />

  <app-button (click)="doSignUp()">Create now</app-button>
}

@if (progress.state === 'progress') {
  <app-progress>
    @if (progress.detail.step === WebAuthnSignUpProgressStep.CreatingUserCredential) {
      <span>Creating user credential...</span>
    }
    @if (progress.detail.step === WebAuthnSignUpProgressStep.ValidatingUserCredential) {
      <span>Validating user credential...</span>
    }
    @if (progress.detail.step === WebAuthnSignUpProgressStep.FinalizingCredential) {
      <span>Finalizing credential...</span>
    }
    @if (progress.detail.step === WebAuthnSignUpProgressStep.Signing) {
      <span>Signing request...</span>
    }
    @if (progress.detail.step === WebAuthnSignUpProgressStep.FinalizingSession) {
      <span>Finalizing session...</span>
    }
    @if (progress.detail.step === WebAuthnSignUpProgressStep.RegisteringUser) {
      <span>Registering user...</span>
    }
  </app-progress>
}

// templates/nextjs-example/src/components/passkey/create-passkey.tsx
import { Button } from "@/components/button";
import {
  WebAuthnSignUpProgressStep,
  type SignProgress,
  type SignProgressFn,
  signUp,
} from "@junobuild/core";
import { useEffect, useState } from "react";
import { Progress } from "@/components/passkey/progress";
import { PasskeyProps } from "@/types/passkey";

type ProgressSignUp =
  | {
      state: "init" | "setup" | "hidden";
    }
  | {
      state: "progress";
      detail: SignProgress<WebAuthnSignUpProgressStep>;
    };

export const CreatePasskey = ({
  progress: wizardProgress,
  onProgress: wizardOnProgress,
}: PasskeyProps) => {
  const [progress, setProgress] = useState<ProgressSignUp>({ state: "init" });
  const [inputText, setInputText] = useState("");

  const onProgress: SignProgressFn<WebAuthnSignUpProgressStep> = (progress) =>
    wizardOnProgress({ signUp: progress });

  useEffect(() => {
    if (wizardProgress === undefined) {
      setProgress({ state: "init" });
      return;
    }

    setProgress(
      "signUp" in wizardProgress
        ? { state: "progress", detail: wizardProgress.signUp }
        : "setup" in wizardProgress
          ? { state: "setup" }
          : { state: "hidden" },
    );
  }, [wizardProgress]);

  const goToSetup = () => {
    wizardOnProgress({ setup: null });
  };

  const doSignUp = async () => {
    try {
      await signUp({
        webauthn: {
          options: {
            onProgress,
            ...(inputText !== "" && {
              passkey: {
                user: {
                  displayName: inputText,
                },
              },
            }),
          },
        },
      });
    } catch (error: unknown) {
      wizardOnProgress(undefined);

      // IRL the error would be gracefully displayed to the user unless
      // it is one to ignore - for example when the user cancel the flow.
      throw error;
    }
  };

  return (
    <>
      {progress.state === "init" ? (
        <>
          <p>
            First time here? Use your device (Face ID, Windows Hello, or screen
            lock) to get in.
          </p>

          <Button onClick={goToSetup}>Create a new passkey</Button>
        </>
      ) : progress.state === "setup" ? (
        <>
          <p>Want to give it a nickname so you&apos;ll spot it easily later?</p>

          <input
            className="mx-0 mt-2 mb-6 block w-full resize-none rounded-sm border-[3px] border-black bg-white px-3 py-1.5 text-base font-normal shadow-[5px_5px_0px_rgba(0,0,0,1)] focus:outline-hidden"
            placeholder="An optional nickname"
            onChange={(e) => {
              setInputText(e.target.value);
            }}
            value={inputText}
          ></input>

          <Button onClick={doSignUp}>Create now</Button>
        </>
      ) : progress.state === "progress" ? (
        <Progress>
          {progress?.detail.step ===
            WebAuthnSignUpProgressStep.CreatingUserCredential && (
            <span>Creating user credential...</span>
          )}
          {progress?.detail.step ===
            WebAuthnSignUpProgressStep.ValidatingUserCredential && (
            <span>Validating user credential...</span>
          )}
          {progress?.detail.step ===
            WebAuthnSignUpProgressStep.FinalizingCredential && (
            <span>Finalizing credential...</span>
          )}
          {progress?.detail.step === WebAuthnSignUpProgressStep.Signing && (
            <span>Signing request....</span>
          )}
          {progress?.detail.step ===
            WebAuthnSignUpProgressStep.FinalizingSession && (
            <span>Finalizing session...</span>
          )}
          {progress?.detail.step ===
            WebAuthnSignUpProgressStep.RegisteringUser && (
            <span>Registering user...</span>
          )}
        </Progress>
      ) : null}
    </>
  );
};
