// templates/vue-example/src/components/Auth.vue
<script setup lang="ts">
import { useAuthStore } from '@/stores/auth.store'
import { storeToRefs } from 'pinia'
import LoginWithII from './LoginWithII.vue'
import Passkey from './passkey/Passkey.vue'
import Logout from './Logout.vue'
import LoginWithGoogle from '@/components/LoginWithGoogle.vue'

const store = useAuthStore()
const { user } = storeToRefs(store)
</script>

<template>
  <template v-if="user !== undefined && user !== null">
    <div>
      <slot />

      <Logout />
    </div>
  </template>

  <template v-else>
    <div class="gap flex flex-col">
      <LoginWithGoogle />

      <Passkey />

      <LoginWithII />
    </div>
  </template>
</template>

// templates/nextjs-example/src/components/auth.tsx
import { LoginWithII } from "@/components/login-with-ii";
import { Logout } from "@/components/logout";
import { onAuthStateChange, type User } from "@junobuild/core";
import { createContext, useEffect, useState, type ReactNode } from "react";
import { Passkey } from "@/components/passkey/passkey";
import { LoginWithGoogle } from "@/components/login-with-google";

export const AuthContext = createContext<{ user: User | undefined | null }>({
  user: undefined,
});

interface AuthProps {
  children: ReactNode;
}

export const Auth = ({ children }: AuthProps) => {
  const [user, setUser] = useState<User | undefined | null>(undefined);

  useEffect(() => {
    const sub = onAuthStateChange((user) => {
      setUser(user);
    });

    return () => {
      sub();
    };
  }, []);

  return (
    <AuthContext.Provider value={{ user }}>
      {user !== undefined && user !== null ? (
        <div>
          {children}

          <Logout />
        </div>
      ) : (
        <div className="gap flex flex-col">
          <LoginWithGoogle />
          <Passkey />
          <LoginWithII />
        </div>
      )}
    </AuthContext.Provider>
  );
};
