// templates/vue-example/src/components/passkey/Passkey.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import type { PasskeyProgress } from '@/types/passkey.ts'
import { isWebAuthnAvailable } from '@junobuild/core'
import Button from '@/components/Button.vue'
import Backdrop from '@/components/Backdrop.vue'
import CreatePasskey from '@/components/passkey/CreatePasskey.vue'
import UsePasskey from '@/components/passkey/UsePasskey.vue'

const passkeySupported = ref(true)
const showModal = ref(false)
const progress = ref<PasskeyProgress | undefined>(undefined)

onMounted(async () => {
  passkeySupported.value = await isWebAuthnAvailable()
})

const start = () => {
  progress.value = undefined
  showModal.value = true
}

const close = () => {
  showModal.value = false
  progress.value = undefined
}

const onProgress = (p: PasskeyProgress | undefined) => {
  progress.value = p
}
</script>

<template>
  <template v-if="passkeySupported">
    <Button @click="start">Continue with Passkey</Button>
  </template>

  <template v-if="showModal">
    <div
      class="animate-fade fixed inset-0 z-50 p-16 md:px-24 md:py-44"
      role="dialog"
      aria-modal="true"
      aria-labelledby="modalTitle"
    >
      <div
        class="w-full max-w-md rounded-sm border-[3px] border-black bg-white px-4 py-3 shadow-[5px_5px_0px_rgba(0,0,0,1)]"
      >
        <template v-if="progress === undefined || 'setup' in progress">
          <div class="flex items-start justify-between">
            <h2 id="modalTitle" class="text-xl font-bold text-gray-900 sm:text-2xl">Hey 👋</h2>

            <button
              type="button"
              class="-me-4 -mt-4 rounded-full p-2 text-gray-400 transition-colors hover:bg-gray-50 hover:text-gray-600 focus:outline-none"
              aria-label="Close"
              @click="close"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="size-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  stroke-width="2"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>
        </template>

        <div class="mt-4">
          <CreatePasskey :progress="progress" :onProgress="onProgress" />

          <UsePasskey :progress="progress" :onProgress="onProgress" />
        </div>
      </div>
    </div>

    <Backdrop />
  </template>
</template>

// templates/angular-example/src/app/components/passkey/passkey/passkey.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-passkey',
  templateUrl: './passkey.component.html',
})
export class PasskeyComponent {}

@if (passkeySupported) {
  <app-button (click)="start()">Continue with Passkey</app-button>
}

@if (showModal) {
  <div
    class="animate-fade fixed inset-0 z-50 p-16 md:px-24 md:py-44"
    role="dialog"
    aria-modal="true"
    aria-labelledby="modalTitle"
  >
    <div
      class="w-full max-w-md rounded-sm border-[3px] border-black bg-white px-4 py-3 shadow-[5px_5px_0px_rgba(0,0,0,1)]"
    >
      @if (progress === undefined || "setup" in progress) {
        <div class="flex items-start justify-between">
          <h2
            id="modalTitle"
            class="text-xl font-bold text-gray-900 sm:text-2xl"
          >
            Hey 👋
          </h2>

          <button
            type="button"
            class="-me-4 -mt-4 rounded-full p-2 text-gray-400 transition-colors hover:bg-gray-50 hover:text-gray-600 focus:outline-none"
            aria-label="Close"
            (click)="close()"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="size-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>
      }

      <div class="mt-4">
        <app-create-passkey
          [wizardProgress]="progress"
          (wizardOnProgress)="onProgress($event)"
        ></app-create-passkey>

        <app-use-passkey
          [wizardProgress]="progress"
          (wizardOnProgress)="onProgress($event)"
        ></app-use-passkey>
      </div>
    </div>
  </div>

  <app-backdrop></app-backdrop>
}
