// templates/nextjs-example/src/components/auth.tsx
import { Login } from "@/components/login";
import { Logout } from "@/components/logout";
import { onAuthStateChange, type User } from "@junobuild/core";
import { createContext, useEffect, useState, type ReactNode } from "react";
import { Passkey } from "@/components/passkey/passkey";

export const AuthContext = createContext<{ user: User | undefined | null }>({
  user: undefined,
});

interface AuthProps {
  children: ReactNode;
}

export const Auth = ({ children }: AuthProps) => {
  const [user, setUser] = useState<User | undefined | null>(undefined);

  useEffect(() => {
    const sub = onAuthStateChange((user) => {
      setUser(user);
    });

    return () => {
      sub();
    };
  }, []);

  return (
    <AuthContext.Provider value={{ user }}>
      {user !== undefined && user !== null ? (
        <div>
          {children}

          <Logout />
        </div>
      ) : (
        <div className="gap flex flex-col">
          <Passkey />
          <Login />
        </div>
      )}
    </AuthContext.Provider>
  );
};

// templates/sveltekit-example/src/lib/components/Auth.svelte
<script lang="ts">
	import { onDestroy, onMount, type Snippet } from 'svelte';
	import { onAuthStateChange } from '@junobuild/core';
	import { userStore } from '$lib/stores/user.store';
	import { userSignedIn } from '$lib/derived/user.derived';
	import Logout from '$lib/components/Logout.svelte';
	import Login from '$lib/components/Login.svelte';
	import Passkey from '$lib/components/passkey/Passkey.svelte';

	interface Props {
		children: Snippet;
	}

	let { children }: Props = $props();

	let unsubscribe: (() => void) | undefined = undefined;

	onMount(() => (unsubscribe = onAuthStateChange((user) => userStore.set(user))));

	const automaticSignOut = () => console.log('Automatically signed out because session expired');

	onDestroy(() => unsubscribe?.());
</script>

<svelte:window onjunoSignOutAuthTimer={automaticSignOut} />

{#if $userSignedIn}
	<div>
		{@render children()}

		<Logout />
	</div>
{:else}
	<div class="gap flex flex-col">
		<Passkey />

		<Login />
	</div>
{/if}
