// templates/vue-example/src/components/Login.vue
<script setup lang="ts">
import { signIn } from '@junobuild/core'
import Button from '@/components/Button.vue'

const signInWithDev = async () => {
  // Sign in for local development and E2E only
  await signIn({
    dev: {},
  });
}
</script>

<template>
  <Button @click="signInWithDev">Sign in for dev</Button>
</template>

// templates/sveltekit-example/src/lib/components/Login.svelte
<script lang="ts">
	import Button from '$lib/components/Button.svelte';
	import { signIn } from '@junobuild/core';

	const signInWithDev = async () => {
		// Sign in for local development and E2E only
		await signIn({
			dev: {}
		});
	};
</script>

<Button onclick={signInWithDev}>Sign in for dev</Button>
